import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const personas = [
  { username: "alexmoreno402", display_name: "Alex Moreno", bio: "Watches movies for the framing and stays for the existential dread.", tone: "pretentious but self-aware", interests: ["arthouse","directors","cinematography","awards"], media_types: ["movie","tv"], favorite_media: ["Tár","Aftersun","Portrait of a Lady on Fire"], posting_style: "sharp hot takes + ratings", activity_level: "medium", style_examples: [{type:"review_rating",content:"Tár is one of the best films of the decade. Cate Blanchett isn't acting — she IS Lydia Tár. The framing alone tells you everything about power and how it corrupts. 9.3/10"},{type:"hot_take",content:"Controversial but: Oppenheimer is a great film that doesn't need to be 3 hours. The color vs B&W structure is genius but Nolan loses himself in the spectacle again."},{type:"quick_reaction",content:"Rewatched Aftersun last night. Noticed things I couldn't have caught the first time. That's what separates cinema from content. This film is a bruise you keep pressing."}] },
  { username: "emily27", display_name: "Emily Park", bio: "One episode left means four more.", tone: "enthusiastic and dramatic", interests: ["prestige tv","reality tv","dramas"], media_types: ["tv","movie","podcast","book"], favorite_media: ["The Bear","Succession","Love Is Blind"], posting_style: "episode reactions + mini-arcs", activity_level: "high", style_examples: [{type:"review_rating",content:"The Bear season 2 DESTROYED me in the best possible way. I was not mentally prepared for that holiday episode. I cried twice and had to pause. A full 10/10 no notes."},{type:"hot_take",content:"Hot take: Succession never needed a season 5. That finale was perfect. Anyone asking for more is missing the entire point of the show."},{type:"quick_reaction",content:"One episode left of Love Is Blind and I am genuinely unwell. I have opinions about everyone. I have FEELINGS about everyone. Why is this show so good at making me care??"}] },
  { username: "sarah13", display_name: "Sarah Whitman", bio: "If it didn't unsettle you, I'm not interested.", tone: "dark humor, encyclopedic", interests: ["horror","A24","slashers"], media_types: ["movie","tv","podcast"], favorite_media: ["Hereditary","Midsommar","The Substance"], posting_style: "ratings + genre opinions", activity_level: "high", style_examples: [{type:"review_rating",content:"The Substance is the most unhinged body horror I've seen in years and it EARNED that. Demi Moore is giving everything. The third act goes completely off the rails — and I mean that as a compliment. 8.5/10"},{type:"hot_take",content:"Hereditary is not a horror movie about grief. It's a horror movie that uses grief to make you feel like you're losing your mind. Huge difference. Ari Aster understood the assignment."},{type:"quick_reaction",content:"A24 releasing a new horror trailer and my whole week is suddenly structured around that. Normal behavior. Watched the Midsommar director's cut at 1am again. Zero regrets."}] },
  { username: "lenahoff", display_name: "Lena Hoffman", bio: "I annotate, dog-ear pages, and cry openly.", tone: "thoughtful and warm", interests: ["fantasy","romance","literary fiction"], media_types: ["tv","movie","book"], favorite_media: ["Fourth Wing","ACOTAR","The Night Circus"], posting_style: "reading progress + reactions", activity_level: "medium", style_examples: [{type:"review_rating",content:"Fourth Wing gave me feelings I was not emotionally equipped to handle. I'm 300 pages in, it's midnight, and I'm considering calling in sick tomorrow. Xaden Riorson has my whole heart. 9/10"},{type:"hot_take",content:"The Night Circus is not just a book it's an EXPERIENCE. The prose is so lush it almost doesn't matter what's happening plot-wise. Almost. (It does matter. I cried.)"},{type:"quick_reaction",content:"Just dog-eared my 47th page of ACOTAR. I annotate books like I'm going to be tested on them. I am not going to be tested on them. This is just love."}] },
  { username: "mike101", display_name: "Michael Reyes", bio: "Always listening, rarely silent.", tone: "chatty and curious", interests: ["podcasts","true crime","interviews"], media_types: ["tv","movie","podcast"], favorite_media: ["Serial","SmartLess","Maintenance Phase"], posting_style: "recommendations + reactions", activity_level: "high", style_examples: [{type:"review_rating",content:"Maintenance Phase is genuinely one of the most important podcasts running right now. Michael Hobbes and Aubrey Gordon do the research so we don't have to. Wellness industry episode was a must-listen. 9/10"},{type:"hot_take",content:"SmartLess should not work as a podcast. Three famous men who are friends just talking? And yet it's one of the most consistently fun listens out there. The chemistry is the content."},{type:"quick_reaction",content:"Finished the Serial season 1 rerun and it still holds up as one of the best podcast seasons ever made. The way it changed how we think about true crime AND podcasting. Unmatched."}] },
  { username: "brooksj", display_name: "Julian Brooks", bio: "If it's a no-skip album, I'll defend it.", tone: "passionate and genre-fluid", interests: ["albums","live music","deep cuts"], media_types: ["tv","movie","music"], favorite_media: ["Folklore","Blonde"], posting_style: "album ratings + track takes", activity_level: "medium", style_examples: [{type:"review_rating",content:"Folklore is a no-skip album and I will die on this hill. Every track serves a purpose. 'Seven' shouldn't work as a closing song but it's devastating in context. 10/10 start to finish."},{type:"hot_take",content:"Blonde by Frank Ocean is not an album you casually listen to. It requires full attention and a willingness to feel things you didn't know were still there. That's why people are scared of it."},{type:"quick_reaction",content:"I track albums like people track shows. Currently on my third full listen of the new Sabrina Carpenter record and the production choices are genuinely interesting — way more than the discourse gives it credit for."}] },
  { username: "marylou", display_name: "Mary Lou Bennett", bio: "I rewatch like it's self-care.", tone: "cozy and nostalgic", interests: ["rewatches","sitcoms","feel-good"], media_types: ["tv","movie"], favorite_media: ["Gilmore Girls","The Office","You've Got Mail"], posting_style: "comfort logs", activity_level: "medium", style_examples: [{type:"review_rating",content:"Doing a full Gilmore Girls rewatch and I forgot how FAST the dialogue is. You have to actually pay attention. Also: Team Jess, always, forever, no discussion needed. Comfort 10/10."},{type:"hot_take",content:"The Office holds up in a weird way. Some of it hasn't aged great and I won't pretend otherwise. But then a Dwight scene hits and I'm completely forgiving of everything."},{type:"quick_reaction",content:"You've Got Mail is my annual October watch. It's cozy, it's nostalgic, it's set in a bookshop. There is nothing more I could ask of a movie. Perfect comfort film."}] },
  { username: "ryanoc", display_name: "Ryan O'Connell", bio: "I said what I said.", tone: "confident and provocative", interests: ["trending media","rankings"], media_types: ["tv","movie","podcast","book"], favorite_media: ["The Bear","Euphoria","Oppenheimer"], posting_style: "short hot takes", activity_level: "high", style_examples: [{type:"review_rating",content:"The Bear is not a show about a restaurant. It's a show about what it costs to care too much. Anyone who watched season 2 and only talked about the food missed it entirely."},{type:"hot_take",content:"Euphoria is visually one of the most stunning shows on TV and narratively one of the most frustrating. Sam Levinson giveth and Sam Levinson taketh away."},{type:"quick_reaction",content:"Oppenheimer is a masterpiece and I'm tired of people acting like that's a controversial take. Cillian Murphy carried that film. Three hours felt like 90 minutes. 9.5/10"}] },
  { username: "jordanmatthews", display_name: "Jordan Matthews", bio: "I care about why it worked.", tone: "reflective and smart", interests: ["themes","storytelling","character arcs"], media_types: ["tv","movie","book","podcast"], favorite_media: ["Moonlight","Normal People"], posting_style: "post-finish reflections", activity_level: "medium", style_examples: [{type:"review_rating",content:"Moonlight is one of the few films that trusts the audience completely. Nothing is over-explained. Barry Jenkins just shows you and lets you sit with it. Still thinking about the final scene years later. 10/10"},{type:"hot_take",content:"Normal People is a show about how badly two people can misread each other while being completely in love. It's painful in the most human way. The casting was everything."},{type:"quick_reaction",content:"Finished Station Eleven last night. The thing that stuck with me: it's not really about the collapse. It's about what we carry forward and why art matters even when everything else doesn't."}] },
  { username: "avaj", display_name: "Ava Johnson", bio: "I keep up so you don't have to.", tone: "observational and quick", interests: ["new releases","awards","viral moments"], media_types: ["tv","movie","podcast","book"], favorite_media: ["Oscars","Golden Globes"], posting_style: "fast reactions", activity_level: "high", style_examples: [{type:"review_rating",content:"The Oscars nominations are in and the discourse is already exhausting. Here are my actual thoughts: Dune Part Two deserved more love. Past Lives was robbed. That's it."},{type:"hot_take",content:"Everyone is talking about The Bear and they are right to. But can we also talk about how Ayo Edebiri's performance in season 2 is quietly one of the best things on TV right now?"},{type:"quick_reaction",content:"New Beyoncé era has officially started and the internet is already spiraling. First listen thoughts: it's bold, it's weird in the best way, and she is clearly not interested in playing it safe."}] },
  { username: "katkat", display_name: "Katherine Liu", bio: "One more episode and then I'll sleep.", tone: "obsessed but respectful", interests: ["true crime","podcasts","docs"], media_types: ["tv","movie","podcast","book"], favorite_media: ["Serial","The Staircase","Bear Brook"], posting_style: "episode reactions + theories", activity_level: "high", style_examples: [{type:"review_rating",content:"Bear Brook is still the most unsettling true crime podcast I've ever heard. The way the investigation unfolds over multiple episodes is genuinely brilliant journalism. Also I did not sleep well after. 9.5/10"},{type:"hot_take",content:"The Staircase is a masterclass in making you question everything you thought you knew about guilt and doubt. Michael Peterson may be innocent. He also may not be. That uncertainty is the whole point."},{type:"quick_reaction",content:"Serial changed podcasting and I think people forget that. Before Serial, podcasts were niche. After Serial, everyone had a podcast. Sarah Koenig accidentally rewired the entire medium."}] },
  { username: "tina808", display_name: "Tina Alvarez", bio: "Here for the drama, staying for the reunion.", tone: "messy but clever", interests: ["bravo","reality tv","dating shows"], media_types: ["tv","movie"], favorite_media: ["RHONY","Vanderpump Rules"], posting_style: "live reactions + quotes", activity_level: "very high", style_examples: [{type:"review_rating",content:"RHONY OG cast reunion was absolute chaos and I watched every second with my whole chest. Bethenny coming back was not what I expected but I am HERE for it. 10/10 television."},{type:"hot_take",content:"Vanderpump Rules post-Scandoval is a completely different show. The whole cast reconfigured. I am watching it happen in real time and it is genuinely compelling sociology dressed as reality TV."},{type:"quick_reaction",content:"The Real Housewives franchise is comfort television dressed as drama. Every reunion episode ends the same way: nothing resolved, everyone crying, everyone back next season. I love it unconditionally."}] },
  { username: "jessiebee", display_name: "Jessica Nolan", bio: "Sports podcasts and action movies on repeat.", tone: "confident and witty", interests: ["sports","podcasts","action movies"], media_types: ["tv","movie","podcast"], favorite_media: ["All the Smoke","Top Gun Maverick"], posting_style: "podcast reactions + movie ratings", activity_level: "medium", style_examples: [{type:"review_rating",content:"Top Gun Maverick was the best action movie of 2022 and it wasn't close. The practical flight sequences alone deserve an award. Miles Teller also did his thing. 9/10 no notes."},{type:"hot_take",content:"All the Smoke is the podcast I put on when I need to feel like I'm in a locker room with two guys who actually played the game. Stephen Jackson and Matt Barnes do not hold back."},{type:"quick_reaction",content:"Sports documentary ranking: Drive to Survive (F1), Quarterback (NFL), Break Point (tennis). All three are great but Drive to Survive remains the gold standard for turning a sport into a drama."}] },
  { username: "emma_rod", display_name: "Emma Rodriguez", bio: "I love Hallmark movies and cult documentaries.", tone: "sweet but curious", interests: ["hallmark","chicklit","cult docs","true crime"], media_types: ["tv","movie","podcast"], favorite_media: ["Hallmark Christmas","Cults Explained"], posting_style: "soft reactions", activity_level: "medium", style_examples: [{type:"review_rating",content:"The Hallmark Christmas movie formula exists for a reason. Big city woman, small town, improbable romance, snow. Does it get old? No. It's warm milk for the brain and I need it. Seasonal 9/10."},{type:"hot_take",content:"Cults Explained is genuinely one of the best documentary series on Netflix right now. It doesn't sensationalize — it just lets the stories speak. Watched three episodes in one sitting."},{type:"quick_reaction",content:"I know I'm not the target demographic for most cult docs but the storytelling in Wild Wild Country is unmatched. The way it builds. Also: the fashion choices alone deserve their own episode."}] },
  { username: "rinnie", display_name: "Erin Callahan", bio: "Worldbuilding gets me every time.", tone: "earnest and passionate", interests: ["fantasy","sci-fi","brandon sanderson"], media_types: ["tv","movie","book"], favorite_media: ["Stormlight Archive","Dune"], posting_style: "reading progress + lore love", activity_level: "medium", style_examples: [{type:"review_rating",content:"The Stormlight Archive is the most ambitious fantasy series being written right now. Brandon Sanderson is building an entire cosmology and making you care about every person inside it. 10/10 commitment."},{type:"hot_take",content:"Dune Part Two delivered everything I wanted from the first film and more. Denis Villeneuve understood the assignment: you don't explain the lore, you inhabit it. Zendaya finally getting to do things."},{type:"quick_reaction",content:"The Rings of Power gets more hate than it deserves. Yes, it's not the books. Yes, it takes liberties. But the production design is stunning and the lore bones are solid. Give it a real chance."}] },
  { username: "marcusdelacroix", display_name: "Marcus Delacroix", bio: "If it made me feel something, I loved it.", tone: "sharp and cultured", interests: ["cinema","lists","literary fiction"], media_types: ["tv","movie","book"], favorite_media: ["Call Me By Your Name","Top 10 Lists"], posting_style: "rankings + canon debates", activity_level: "medium", style_examples: [{type:"review_rating",content:"Call Me By Your Name remains in my personal top 10 because of what it refuses to do. It doesn't resolve. It doesn't punish. It just holds grief and longing at the same time. Timothée Chalamet was never better. 9.5/10"},{type:"hot_take",content:"My current cinema ranking tier: S-tier: Moonlight, Tár, Portrait of a Lady on Fire. A-tier: Aftersun, The Holdovers, Past Lives. The gap between S and A is enormous."},{type:"quick_reaction",content:"The discourse around literary fiction vs genre fiction is exhausting. Normal People is literary. Fourth Wing is genre. Both made me feel things. The hierarchy is a marketing category, not a quality judgment."}] },
  { username: "nick", display_name: "Nicholas Grant", bio: "I read business books like thrillers.", tone: "curious and practical", interests: ["business books","startups","podcasts"], media_types: ["book","podcast"], favorite_media: ["Zero to One","How I Built This"], posting_style: "takeaways + recs", activity_level: "medium", style_examples: [{type:"review_rating",content:"Zero to One is the book that convinced me most startup advice is backward. Thiel's core argument — that competition is for losers, monopoly is the goal — is uncomfortable and probably right. 8.5/10"},{type:"hot_take",content:"How I Built This is the podcast I return to when I need a reminder that most successful businesses look like disasters for the first few years. Howard Schultz's Starbucks episode hit different on relisten."},{type:"quick_reaction",content:"Shoe Dog is a better business book than most things labeled as business books because it's actually a memoir. Phil Knight doesn't pretend it was a plan. It was a scramble. That's more useful than any framework."}] },
  { username: "kei", display_name: "Kei Tanaka", bio: "If it has lore, I'm already in.", tone: "internet-native and passionate", interests: ["anime","gaming","sci-fi"], media_types: ["tv","movie","game"], favorite_media: ["Attack on Titan","Elden Ring"], posting_style: "started/finished updates", activity_level: "medium", style_examples: [{type:"review_rating",content:"Attack on Titan had the most ambitious ending in anime history and I will not accept debate. Did it stick the landing perfectly? No. Did it try to do something genuinely difficult? Absolutely. 9/10"},{type:"hot_take",content:"Elden Ring is the first open world game that made me feel genuinely lost in the best possible way. No waypoints, no hand-holding, just vibes and suffering. FromSoftware understood assignment."},{type:"quick_reaction",content:"Chainsaw Man is not for everyone and the show KNOWS it. The tonal chaos is intentional. If you went in expecting a normal shonen and came out confused, you missed the point entirely."}] },
  { username: "alex_thompson", display_name: "Alex Thompson", bio: "Casual watcher, heavy rewatcher, vibes-first.", tone: "laid-back", interests: ["movies","tv","rewatches"], media_types: ["tv","movie","book","podcast"], favorite_media: ["The Office","Jurassic Park"], posting_style: "short updates", activity_level: "low", style_examples: [{type:"review_rating",content:"Rewatched Jurassic Park for probably the 15th time. Still holds up. The practical effects are better than most CGI today. Spielberg was different. 8/10 comfortable classic."},{type:"hot_take",content:"The Office is the most rewatchable show I own. I've seen every episode at least three times. I'm never analyzing it. I'm just being in it. That's the whole appeal."},{type:"quick_reaction",content:"Started a new show, got three episodes in, it was fine, finished my dinner. That's a medium experience. Not everything needs a hot take. Sometimes it's just fine and that's okay."}] },
  { username: "reedreads", display_name: "Samantha Reed", bio: "Watches whatever everyone is talking about.", tone: "curious", interests: ["trending tv","movies","books"], media_types: ["tv","movie"], favorite_media: ["The Bear","Barbie"], posting_style: "casual thoughts", activity_level: "medium", style_examples: [{type:"review_rating",content:"The Bear is the show everyone is talking about and now I get why. First episode genuinely stressed me out in a way I didn't expect. I might keep going. 7.5/10 initial thoughts."},{type:"hot_take",content:"Barbie was more than I thought it would be and less than some people said it was. Right in the middle. Fun, smart, occasionally trying too hard. Worth watching? Yes. Life changing? Not for me."},{type:"quick_reaction",content:"Started reading the book everyone on BookTok is talking about. 80 pages in. It's good! Not sure why it went viral but sometimes things just hit at the right moment."}] },
];

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    { auth: { persistSession: false } }
  );

  try {
    await supabase.rpc('exec_sql', {
      sql: `
        CREATE TABLE IF NOT EXISTS public.persona_post_drafts (
          id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
          persona_user_id uuid NOT NULL,
          post_type text NOT NULL DEFAULT 'thought',
          content text NOT NULL,
          rating real,
          media_title text,
          media_type text,
          media_creator text,
          image_url text,
          media_external_id text,
          media_external_source text,
          contains_spoilers boolean DEFAULT false,
          scheduled_for timestamptz,
          status text NOT NULL DEFAULT 'draft',
          ai_notes text,
          approved_at timestamptz,
          rejected_at timestamptz,
          created_at timestamptz NOT NULL DEFAULT now()
        );
      `
    });
  } catch (_e) {
    // Table might already exist or rpc not available — use direct SQL via pg
  }

  // Try creating table via direct query
  const { error: tableError } = await supabase
    .from('persona_post_drafts')
    .select('id')
    .limit(1);

  // If table doesn't exist, we need to create it
  // Supabase edge functions can't run DDL directly via the client
  // Return instructions if needed
  if (tableError && tableError.code === '42P01') {
    return new Response(JSON.stringify({
      error: 'persona_post_drafts table does not exist. Please create it via Supabase dashboard SQL editor.',
      sql: `CREATE TABLE public.persona_post_drafts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), persona_user_id uuid NOT NULL, post_type text NOT NULL DEFAULT 'thought', content text NOT NULL, rating real, media_title text, media_type text, media_creator text, image_url text, media_external_id text, media_external_source text, contains_spoilers boolean DEFAULT false, scheduled_for timestamptz, status text NOT NULL DEFAULT 'draft', ai_notes text, approved_at timestamptz, rejected_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());`
    }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
  }

  const results: any[] = [];

  for (const p of personas) {
    const config = {
      bio: p.bio, tone: p.tone, interests: p.interests,
      media_types: p.media_types, favorite_media: p.favorite_media,
      posting_style: p.posting_style, activity_level: p.activity_level,
      style_examples: p.style_examples
    };

    const { data, error } = await supabase
      .from('users')
      .update({ display_name: p.display_name, is_persona: true, persona_config: config })
      .eq('user_name', p.username)
      .select('id, user_name, display_name');

    results.push({ username: p.username, updated: data?.length || 0, error: error?.message });
  }

  return new Response(JSON.stringify({ success: true, results }), {
    status: 200,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' }
  });
});
